- hosts: all
  tasks:
    - name: Test Connection
      ping:
      timeout: 600
    - name: Check that you can connect (GET) to the API and it returns a status 200
      ansible.builtin.uri:
        url: "{{ _ssm_masterNodeUrl }}/api/ping"
